export const ADD_MAIN_LINK = 'ADD_MAIN_LINK'
export const CONNECT_SUB_TO_MAIN = 'CONNECT_SUB_TO_MAIN'

export const ADD_SUB_LINK = 'ADD_SUB_LINK'
export const DELETE_SUB_LINK = 'DELETE_SUB_LINK'
export const EDIT_SUB_LINK = 'DELETE_SUB_LINK'

export const SELECT_MAIN_LINK = 'SELECT_MAIN_LINK'
export const SELECT_SUB_LINK = 'SELECT_SUB_LINK'

export const VIEW_CONTENT = 'VIEW_CONTENT'

export const CHANGE_INPUT_MODE = 'CHANGE_INPUT_MODE'
export const DEFAULT_INPUT_MODE = 'DEFAULT_INPUT_MODE'